/*
Blockchain Indexer API

Testing AccountsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package maestro

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/blinklabs-io/maestro-go"
)

func Test_maestro_AccountsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AccountsAPIService AccountAddresses", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stakeAddress string

		resp, httpRes, err := apiClient.AccountsAPI.AccountAddresses(context.Background(), stakeAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccountsAPIService AccountAssets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stakeAddress string

		resp, httpRes, err := apiClient.AccountsAPI.AccountAssets(context.Background(), stakeAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccountsAPIService AccountHistory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stakeAddress string

		resp, httpRes, err := apiClient.AccountsAPI.AccountHistory(context.Background(), stakeAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccountsAPIService AccountInfo", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stakeAddress string

		resp, httpRes, err := apiClient.AccountsAPI.AccountInfo(context.Background(), stakeAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccountsAPIService AccountRewards", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stakeAddress string

		resp, httpRes, err := apiClient.AccountsAPI.AccountRewards(context.Background(), stakeAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccountsAPIService AccountUpdates", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stakeAddress string

		resp, httpRes, err := apiClient.AccountsAPI.AccountUpdates(context.Background(), stakeAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
