/*
Blockchain Indexer API

Testing TransactionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package maestro

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/blinklabs-io/maestro-go"
)

func Test_maestro_TransactionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TransactionsAPIService AddressByTxo", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var txHash string
		var index int32

		resp, httpRes, err := apiClient.TransactionsAPI.AddressByTxo(context.Background(), txHash, index).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransactionsAPIService IogTxSubmit", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TransactionsAPI.IogTxSubmit(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransactionsAPIService MaestroTxSubmit", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TransactionsAPI.MaestroTxSubmit(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransactionsAPIService TxCborByTxHash", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var txHash string

		resp, httpRes, err := apiClient.TransactionsAPI.TxCborByTxHash(context.Background(), txHash).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransactionsAPIService TxInfo", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var txHash string

		resp, httpRes, err := apiClient.TransactionsAPI.TxInfo(context.Background(), txHash).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TransactionsAPIService UtxoByTxoRef", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var txHash string
		var index int32

		resp, httpRes, err := apiClient.TransactionsAPI.UtxoByTxoRef(context.Background(), txHash, index).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
