/*
Blockchain Indexer API

Testing AddressesApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/blinklabs-io/maestro-go"
)

func Test_openapi_AddressesApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AddressesApiService AddressUtxos", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var address string

		resp, httpRes, err := apiClient.AddressesApi.AddressUtxos(context.Background(), address).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AddressesApiService DecodeAddress", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var address string

		resp, httpRes, err := apiClient.AddressesApi.DecodeAddress(context.Background(), address).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AddressesApiService TxCountByAddress", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var address string

		resp, httpRes, err := apiClient.AddressesApi.TxCountByAddress(context.Background(), address).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AddressesApiService UtxoRefsAtAddress", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var address string

		resp, httpRes, err := apiClient.AddressesApi.UtxoRefsAtAddress(context.Background(), address).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AddressesApiService UtxosByAddresses", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AddressesApi.UtxosByAddresses(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
