/*
Blockchain Indexer API

Testing AccountsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_AccountsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AccountsApiService AccountAddresses", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stakeAddress string

		resp, httpRes, err := apiClient.AccountsApi.AccountAddresses(context.Background(), stakeAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccountsApiService AccountAssets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stakeAddress string

		resp, httpRes, err := apiClient.AccountsApi.AccountAssets(context.Background(), stakeAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccountsApiService AccountHistory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stakeAddress string

		resp, httpRes, err := apiClient.AccountsApi.AccountHistory(context.Background(), stakeAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccountsApiService AccountInfo", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stakeAddress string

		resp, httpRes, err := apiClient.AccountsApi.AccountInfo(context.Background(), stakeAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccountsApiService AccountRewards", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stakeAddress string

		resp, httpRes, err := apiClient.AccountsApi.AccountRewards(context.Background(), stakeAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AccountsApiService AccountUpdates", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var stakeAddress string

		resp, httpRes, err := apiClient.AccountsApi.AccountUpdates(context.Background(), stakeAddress).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
