/*
Blockchain Indexer API

The **Maestro Blockchain Indexer API** follows the [REST](https://restfulapi.net/) paradigm. To interact with Mapi, please  head over to [Dashboards](https://dashboard.gomaestro.org), create an API project, and copy its associated long-lived API key into your request header.  Your Mapi project is rate-limited based on your API package tier. Please see the available [Packages](https://dashboard.gomaestro.org/pricing) for more details or to upgrade your plan.  Example `GET` request for retrieving the chain tip: ``` curl -X GET --header \"api-key: <your_project_api_key>\" https://mainnet.gomaestro-api.org/v0/chain-tip ```  Example `POST` request for submitting a transaction: ``` curl -X POST --header \"Content-Type: application/cbor\" --header \"api-key: <your_project_api_key>\" --data @tx.signed https://mainnet.gomaestro-api.org/v0/transactions ```

API version: V0
Contact: info@gomaestro.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package maestro

import (
	"encoding/json"
)

// checks if the StakeDelegCert type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StakeDelegCert{}

// StakeDelegCert Certificate for stake key delegation
type StakeDelegCert struct {
	// Index of the certificate in the transaction
	CertIndex int32 `json:"cert_index"`
	// Pool ID of the stake pool the stake key is delegating to
	PoolId string `json:"pool_id"`
	// Stake address corresponding to stake key being delegated
	StakeAddress string `json:"stake_address"`
}

// NewStakeDelegCert instantiates a new StakeDelegCert object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStakeDelegCert(certIndex int32, poolId string, stakeAddress string) *StakeDelegCert {
	this := StakeDelegCert{}
	this.CertIndex = certIndex
	this.PoolId = poolId
	this.StakeAddress = stakeAddress
	return &this
}

// NewStakeDelegCertWithDefaults instantiates a new StakeDelegCert object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStakeDelegCertWithDefaults() *StakeDelegCert {
	this := StakeDelegCert{}
	return &this
}

// GetCertIndex returns the CertIndex field value
func (o *StakeDelegCert) GetCertIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CertIndex
}

// GetCertIndexOk returns a tuple with the CertIndex field value
// and a boolean to check if the value has been set.
func (o *StakeDelegCert) GetCertIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CertIndex, true
}

// SetCertIndex sets field value
func (o *StakeDelegCert) SetCertIndex(v int32) {
	o.CertIndex = v
}

// GetPoolId returns the PoolId field value
func (o *StakeDelegCert) GetPoolId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolId
}

// GetPoolIdOk returns a tuple with the PoolId field value
// and a boolean to check if the value has been set.
func (o *StakeDelegCert) GetPoolIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolId, true
}

// SetPoolId sets field value
func (o *StakeDelegCert) SetPoolId(v string) {
	o.PoolId = v
}

// GetStakeAddress returns the StakeAddress field value
func (o *StakeDelegCert) GetStakeAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StakeAddress
}

// GetStakeAddressOk returns a tuple with the StakeAddress field value
// and a boolean to check if the value has been set.
func (o *StakeDelegCert) GetStakeAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StakeAddress, true
}

// SetStakeAddress sets field value
func (o *StakeDelegCert) SetStakeAddress(v string) {
	o.StakeAddress = v
}

func (o StakeDelegCert) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StakeDelegCert) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cert_index"] = o.CertIndex
	toSerialize["pool_id"] = o.PoolId
	toSerialize["stake_address"] = o.StakeAddress
	return toSerialize, nil
}

type NullableStakeDelegCert struct {
	value *StakeDelegCert
	isSet bool
}

func (v NullableStakeDelegCert) Get() *StakeDelegCert {
	return v.value
}

func (v *NullableStakeDelegCert) Set(val *StakeDelegCert) {
	v.value = val
	v.isSet = true
}

func (v NullableStakeDelegCert) IsSet() bool {
	return v.isSet
}

func (v *NullableStakeDelegCert) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStakeDelegCert(val *StakeDelegCert) *NullableStakeDelegCert {
	return &NullableStakeDelegCert{value: val, isSet: true}
}

func (v NullableStakeDelegCert) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStakeDelegCert) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


