/*
Blockchain Indexer API

The **Maestro Blockchain Indexer API** follows the [REST](https://restfulapi.net/) paradigm. To interact with Mapi, please  head over to [Dashboards](https://dashboard.gomaestro.org), create an API project, and copy its associated long-lived API key into your request header.  Your Mapi project is rate-limited based on your API package tier. Please see the available [Packages](https://dashboard.gomaestro.org/pricing) for more details or to upgrade your plan.  Example `GET` request for retrieving the chain tip: ``` curl -X GET --header \"api-key: <your_project_api_key>\" https://mainnet.gomaestro-api.org/v0/chain-tip ```  Example `POST` request for submitting a transaction: ``` curl -X POST --header \"Content-Type: application/cbor\" --header \"api-key: <your_project_api_key>\" --data @tx.signed https://mainnet.gomaestro-api.org/v0/transactions ```

API version: V0
Contact: info@gomaestro.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package maestro

import (
	"encoding/json"
)

// checks if the TxCbor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TxCbor{}

// TxCbor Transaction bytes
type TxCbor struct {
	// Hex encoded transaction CBOR bytes
	Cbor string `json:"cbor"`
}

// NewTxCbor instantiates a new TxCbor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTxCbor(cbor string) *TxCbor {
	this := TxCbor{}
	this.Cbor = cbor
	return &this
}

// NewTxCborWithDefaults instantiates a new TxCbor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTxCborWithDefaults() *TxCbor {
	this := TxCbor{}
	return &this
}

// GetCbor returns the Cbor field value
func (o *TxCbor) GetCbor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cbor
}

// GetCborOk returns a tuple with the Cbor field value
// and a boolean to check if the value has been set.
func (o *TxCbor) GetCborOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cbor, true
}

// SetCbor sets field value
func (o *TxCbor) SetCbor(v string) {
	o.Cbor = v
}

func (o TxCbor) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TxCbor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cbor"] = o.Cbor
	return toSerialize, nil
}

type NullableTxCbor struct {
	value *TxCbor
	isSet bool
}

func (v NullableTxCbor) Get() *TxCbor {
	return v.value
}

func (v *NullableTxCbor) Set(val *TxCbor) {
	v.value = val
	v.isSet = true
}

func (v NullableTxCbor) IsSet() bool {
	return v.isSet
}

func (v *NullableTxCbor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTxCbor(val *TxCbor) *NullableTxCbor {
	return &NullableTxCbor{value: val, isSet: true}
}

func (v NullableTxCbor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTxCbor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


