/*
Blockchain Indexer API

The **Maestro Blockchain Indexer API** follows the [REST](https://restfulapi.net/) paradigm. To interact with Mapi, please  head over to [Dashboards](https://dashboard.gomaestro.org), create an API project, and copy its associated long-lived API key into your request header.  Your Mapi project is rate-limited based on your API package tier. Please see the available [Packages](https://dashboard.gomaestro.org/pricing) for more details or to upgrade your plan.  Example `GET` request for retrieving the chain tip: ``` curl -X GET --header \"api-key: <your_project_api_key>\" https://mainnet.gomaestro-api.org/v0/chain-tip ```  Example `POST` request for submitting a transaction: ``` curl -X POST --header \"Content-Type: application/cbor\" --header \"api-key: <your_project_api_key>\" --data @tx.signed https://mainnet.gomaestro-api.org/v0/transactions ```

API version: V0
Contact: info@gomaestro.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package maestro

import (
	"encoding/json"
)

// checks if the Withdrawal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Withdrawal{}

// Withdrawal struct for Withdrawal
type Withdrawal struct {
	Amount int64 `json:"amount"`
	StakeAddress string `json:"stake_address"`
}

// NewWithdrawal instantiates a new Withdrawal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWithdrawal(amount int64, stakeAddress string) *Withdrawal {
	this := Withdrawal{}
	this.Amount = amount
	this.StakeAddress = stakeAddress
	return &this
}

// NewWithdrawalWithDefaults instantiates a new Withdrawal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWithdrawalWithDefaults() *Withdrawal {
	this := Withdrawal{}
	return &this
}

// GetAmount returns the Amount field value
func (o *Withdrawal) GetAmount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *Withdrawal) GetAmountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *Withdrawal) SetAmount(v int64) {
	o.Amount = v
}

// GetStakeAddress returns the StakeAddress field value
func (o *Withdrawal) GetStakeAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StakeAddress
}

// GetStakeAddressOk returns a tuple with the StakeAddress field value
// and a boolean to check if the value has been set.
func (o *Withdrawal) GetStakeAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StakeAddress, true
}

// SetStakeAddress sets field value
func (o *Withdrawal) SetStakeAddress(v string) {
	o.StakeAddress = v
}

func (o Withdrawal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Withdrawal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	toSerialize["stake_address"] = o.StakeAddress
	return toSerialize, nil
}

type NullableWithdrawal struct {
	value *Withdrawal
	isSet bool
}

func (v NullableWithdrawal) Get() *Withdrawal {
	return v.value
}

func (v *NullableWithdrawal) Set(val *Withdrawal) {
	v.value = val
	v.isSet = true
}

func (v NullableWithdrawal) IsSet() bool {
	return v.isSet
}

func (v *NullableWithdrawal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWithdrawal(val *Withdrawal) *NullableWithdrawal {
	return &NullableWithdrawal{value: val, isSet: true}
}

func (v NullableWithdrawal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWithdrawal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


