/*
Blockchain Indexer API

The **Maestro Blockchain Indexer API** follows the [REST](https://restfulapi.net/) paradigm. To interact with Mapi, please  head over to [Dashboards](https://dashboard.gomaestro.org), create an API project, and copy its associated long-lived API key into your request header.  Your Mapi project is rate-limited based on your API package tier. Please see the available [Packages](https://dashboard.gomaestro.org/pricing) for more details or to upgrade your plan.  Example `GET` request for retrieving the chain tip: ``` curl -X GET --header \"api-key: <your_project_api_key>\" https://mainnet.gomaestro-api.org/v0/chain-tip ```  Example `POST` request for submitting a transaction: ``` curl -X POST --header \"Content-Type: application/cbor\" --header \"api-key: <your_project_api_key>\" --data @tx.signed https://mainnet.gomaestro-api.org/v0/transactions ```

API version: V0
Contact: info@gomaestro.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EraSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EraSummary{}

// EraSummary struct for EraSummary
type EraSummary struct {
	End *Bound `json:"end,omitempty"`
	Parameters EraParameters `json:"parameters"`
	Start Bound `json:"start"`
}

// NewEraSummary instantiates a new EraSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEraSummary(parameters EraParameters, start Bound) *EraSummary {
	this := EraSummary{}
	this.Parameters = parameters
	this.Start = start
	return &this
}

// NewEraSummaryWithDefaults instantiates a new EraSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEraSummaryWithDefaults() *EraSummary {
	this := EraSummary{}
	return &this
}

// GetEnd returns the End field value if set, zero value otherwise.
func (o *EraSummary) GetEnd() Bound {
	if o == nil || IsNil(o.End) {
		var ret Bound
		return ret
	}
	return *o.End
}

// GetEndOk returns a tuple with the End field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EraSummary) GetEndOk() (*Bound, bool) {
	if o == nil || IsNil(o.End) {
		return nil, false
	}
	return o.End, true
}

// HasEnd returns a boolean if a field has been set.
func (o *EraSummary) HasEnd() bool {
	if o != nil && !IsNil(o.End) {
		return true
	}

	return false
}

// SetEnd gets a reference to the given Bound and assigns it to the End field.
func (o *EraSummary) SetEnd(v Bound) {
	o.End = &v
}

// GetParameters returns the Parameters field value
func (o *EraSummary) GetParameters() EraParameters {
	if o == nil {
		var ret EraParameters
		return ret
	}

	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value
// and a boolean to check if the value has been set.
func (o *EraSummary) GetParametersOk() (*EraParameters, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parameters, true
}

// SetParameters sets field value
func (o *EraSummary) SetParameters(v EraParameters) {
	o.Parameters = v
}

// GetStart returns the Start field value
func (o *EraSummary) GetStart() Bound {
	if o == nil {
		var ret Bound
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *EraSummary) GetStartOk() (*Bound, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *EraSummary) SetStart(v Bound) {
	o.Start = v
}

func (o EraSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EraSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.End) {
		toSerialize["end"] = o.End
	}
	toSerialize["parameters"] = o.Parameters
	toSerialize["start"] = o.Start
	return toSerialize, nil
}

type NullableEraSummary struct {
	value *EraSummary
	isSet bool
}

func (v NullableEraSummary) Get() *EraSummary {
	return v.value
}

func (v *NullableEraSummary) Set(val *EraSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableEraSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableEraSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEraSummary(val *EraSummary) *NullableEraSummary {
	return &NullableEraSummary{value: val, isSet: true}
}

func (v NullableEraSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEraSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


