/*
Blockchain Indexer API

The **Maestro Blockchain Indexer API** follows the [REST](https://restfulapi.net/) paradigm. To interact with Mapi, please  head over to [Dashboards](https://dashboard.gomaestro.org), create an API project, and copy its associated long-lived API key into your request header.  Your Mapi project is rate-limited based on your API package tier. Please see the available [Packages](https://dashboard.gomaestro.org/pricing) for more details or to upgrade your plan.  Example `GET` request for retrieving the chain tip: ``` curl -X GET --header \"api-key: <your_project_api_key>\" https://mainnet.gomaestro-api.org/v0/chain-tip ```  Example `POST` request for submitting a transaction: ``` curl -X POST --header \"Content-Type: application/cbor\" --header \"api-key: <your_project_api_key>\" --data @tx.signed https://mainnet.gomaestro-api.org/v0/transactions ```

API version: V0
Contact: info@gomaestro.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package maestro

import (
	"encoding/json"
	"fmt"
)

// DatumOptionType Datum type (inline datum or datum hash)
type DatumOptionType string

// List of DatumOptionType
const (
	DATUMOPTIONTYPE_HASH DatumOptionType = "hash"
	DATUMOPTIONTYPE_INLINE DatumOptionType = "inline"
)

// All allowed values of DatumOptionType enum
var AllowedDatumOptionTypeEnumValues = []DatumOptionType{
	"hash",
	"inline",
}

func (v *DatumOptionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DatumOptionType(value)
	for _, existing := range AllowedDatumOptionTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DatumOptionType", value)
}

// NewDatumOptionTypeFromValue returns a pointer to a valid DatumOptionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDatumOptionTypeFromValue(v string) (*DatumOptionType, error) {
	ev := DatumOptionType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DatumOptionType: valid values are %v", v, AllowedDatumOptionTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DatumOptionType) IsValid() bool {
	for _, existing := range AllowedDatumOptionTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DatumOptionType value
func (v DatumOptionType) Ptr() *DatumOptionType {
	return &v
}

type NullableDatumOptionType struct {
	value *DatumOptionType
	isSet bool
}

func (v NullableDatumOptionType) Get() *DatumOptionType {
	return v.value
}

func (v *NullableDatumOptionType) Set(val *DatumOptionType) {
	v.value = val
	v.isSet = true
}

func (v NullableDatumOptionType) IsSet() bool {
	return v.isSet
}

func (v *NullableDatumOptionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDatumOptionType(val *DatumOptionType) *NullableDatumOptionType {
	return &NullableDatumOptionType{value: val, isSet: true}
}

func (v NullableDatumOptionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDatumOptionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

