/*
Blockchain Indexer API

The **Maestro Blockchain Indexer API** follows the [REST](https://restfulapi.net/) paradigm. To interact with Mapi, please  head over to [Dashboards](https://dashboard.gomaestro.org), create an API project, and copy its associated long-lived API key into your request header.  Your Mapi project is rate-limited based on your API package tier. Please see the available [Packages](https://dashboard.gomaestro.org/pricing) for more details or to upgrade your plan.  Example `GET` request for retrieving the chain tip: ``` curl -X GET --header \"api-key: <your_project_api_key>\" https://mainnet.gomaestro-api.org/v0/chain-tip ```  Example `POST` request for submitting a transaction: ``` curl -X POST --header \"Content-Type: application/cbor\" --header \"api-key: <your_project_api_key>\" --data @tx.signed https://mainnet.gomaestro-api.org/v0/transactions ```

API version: V0
Contact: info@gomaestro.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package maestro

import (
	"encoding/json"
	"fmt"
)

// ScriptType Script type and version
type ScriptType string

// List of ScriptType
const (
	SCRIPTTYPE_NATIVE ScriptType = "native"
	SCRIPTTYPE_PLUTUSV1 ScriptType = "plutusv1"
	SCRIPTTYPE_PLUTUSV2 ScriptType = "plutusv2"
)

// All allowed values of ScriptType enum
var AllowedScriptTypeEnumValues = []ScriptType{
	"native",
	"plutusv1",
	"plutusv2",
}

func (v *ScriptType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ScriptType(value)
	for _, existing := range AllowedScriptTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ScriptType", value)
}

// NewScriptTypeFromValue returns a pointer to a valid ScriptType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewScriptTypeFromValue(v string) (*ScriptType, error) {
	ev := ScriptType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ScriptType: valid values are %v", v, AllowedScriptTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ScriptType) IsValid() bool {
	for _, existing := range AllowedScriptTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ScriptType value
func (v ScriptType) Ptr() *ScriptType {
	return &v
}

type NullableScriptType struct {
	value *ScriptType
	isSet bool
}

func (v NullableScriptType) Get() *ScriptType {
	return v.value
}

func (v *NullableScriptType) Set(val *ScriptType) {
	v.value = val
	v.isSet = true
}

func (v NullableScriptType) IsSet() bool {
	return v.isSet
}

func (v *NullableScriptType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScriptType(val *ScriptType) *NullableScriptType {
	return &NullableScriptType{value: val, isSet: true}
}

func (v NullableScriptType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScriptType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

