/*
Blockchain Indexer API

The **Maestro Blockchain Indexer API** follows the [REST](https://restfulapi.net/) paradigm. To interact with Mapi, please  head over to [Dashboards](https://dashboard.gomaestro.org), create an API project, and copy its associated long-lived API key into your request header.  Your Mapi project is rate-limited based on your API package tier. Please see the available [Packages](https://dashboard.gomaestro.org/pricing) for more details or to upgrade your plan.  Example `GET` request for retrieving the chain tip: ``` curl -X GET --header \"api-key: <your_project_api_key>\" https://mainnet.gomaestro-api.org/v0/chain-tip ```  Example `POST` request for submitting a transaction: ``` curl -X POST --header \"Content-Type: application/cbor\" --header \"api-key: <your_project_api_key>\" --data @tx.signed https://mainnet.gomaestro-api.org/v0/transactions ```

API version: V0
Contact: info@gomaestro.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Utxo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Utxo{}

// Utxo Transaction output
type Utxo struct {
	// Address which controls the UTxO
	Address string `json:"address"`
	Assets []Asset `json:"assets"`
	Datum *DatumOption `json:"datum,omitempty"`
	// UTxO transaction index
	Index int32 `json:"index"`
	ReferenceScript *Script `json:"reference_script,omitempty"`
	// UTxO transaction hash
	TxHash string `json:"tx_hash"`
}

// NewUtxo instantiates a new Utxo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUtxo(address string, assets []Asset, index int32, txHash string) *Utxo {
	this := Utxo{}
	this.Address = address
	this.Assets = assets
	this.Index = index
	this.TxHash = txHash
	return &this
}

// NewUtxoWithDefaults instantiates a new Utxo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUtxoWithDefaults() *Utxo {
	this := Utxo{}
	return &this
}

// GetAddress returns the Address field value
func (o *Utxo) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *Utxo) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *Utxo) SetAddress(v string) {
	o.Address = v
}

// GetAssets returns the Assets field value
func (o *Utxo) GetAssets() []Asset {
	if o == nil {
		var ret []Asset
		return ret
	}

	return o.Assets
}

// GetAssetsOk returns a tuple with the Assets field value
// and a boolean to check if the value has been set.
func (o *Utxo) GetAssetsOk() ([]Asset, bool) {
	if o == nil {
		return nil, false
	}
	return o.Assets, true
}

// SetAssets sets field value
func (o *Utxo) SetAssets(v []Asset) {
	o.Assets = v
}

// GetDatum returns the Datum field value if set, zero value otherwise.
func (o *Utxo) GetDatum() DatumOption {
	if o == nil || IsNil(o.Datum) {
		var ret DatumOption
		return ret
	}
	return *o.Datum
}

// GetDatumOk returns a tuple with the Datum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Utxo) GetDatumOk() (*DatumOption, bool) {
	if o == nil || IsNil(o.Datum) {
		return nil, false
	}
	return o.Datum, true
}

// HasDatum returns a boolean if a field has been set.
func (o *Utxo) HasDatum() bool {
	if o != nil && !IsNil(o.Datum) {
		return true
	}

	return false
}

// SetDatum gets a reference to the given DatumOption and assigns it to the Datum field.
func (o *Utxo) SetDatum(v DatumOption) {
	o.Datum = &v
}

// GetIndex returns the Index field value
func (o *Utxo) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *Utxo) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *Utxo) SetIndex(v int32) {
	o.Index = v
}

// GetReferenceScript returns the ReferenceScript field value if set, zero value otherwise.
func (o *Utxo) GetReferenceScript() Script {
	if o == nil || IsNil(o.ReferenceScript) {
		var ret Script
		return ret
	}
	return *o.ReferenceScript
}

// GetReferenceScriptOk returns a tuple with the ReferenceScript field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Utxo) GetReferenceScriptOk() (*Script, bool) {
	if o == nil || IsNil(o.ReferenceScript) {
		return nil, false
	}
	return o.ReferenceScript, true
}

// HasReferenceScript returns a boolean if a field has been set.
func (o *Utxo) HasReferenceScript() bool {
	if o != nil && !IsNil(o.ReferenceScript) {
		return true
	}

	return false
}

// SetReferenceScript gets a reference to the given Script and assigns it to the ReferenceScript field.
func (o *Utxo) SetReferenceScript(v Script) {
	o.ReferenceScript = &v
}

// GetTxHash returns the TxHash field value
func (o *Utxo) GetTxHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TxHash
}

// GetTxHashOk returns a tuple with the TxHash field value
// and a boolean to check if the value has been set.
func (o *Utxo) GetTxHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TxHash, true
}

// SetTxHash sets field value
func (o *Utxo) SetTxHash(v string) {
	o.TxHash = v
}

func (o Utxo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Utxo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["assets"] = o.Assets
	if !IsNil(o.Datum) {
		toSerialize["datum"] = o.Datum
	}
	toSerialize["index"] = o.Index
	if !IsNil(o.ReferenceScript) {
		toSerialize["reference_script"] = o.ReferenceScript
	}
	toSerialize["tx_hash"] = o.TxHash
	return toSerialize, nil
}

type NullableUtxo struct {
	value *Utxo
	isSet bool
}

func (v NullableUtxo) Get() *Utxo {
	return v.value
}

func (v *NullableUtxo) Set(val *Utxo) {
	v.value = val
	v.isSet = true
}

func (v NullableUtxo) IsSet() bool {
	return v.isSet
}

func (v *NullableUtxo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUtxo(val *Utxo) *NullableUtxo {
	return &NullableUtxo{value: val, isSet: true}
}

func (v NullableUtxo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUtxo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


