/*
Blockchain Indexer API

The **Maestro Blockchain Indexer API** follows the [REST](https://restfulapi.net/) paradigm. To interact with Mapi, please  head over to [Dashboards](https://dashboard.gomaestro.org), create an API project, and copy its associated long-lived API key into your request header.  Your Mapi project is rate-limited based on your API package tier. Please see the available [Packages](https://dashboard.gomaestro.org/pricing) for more details or to upgrade your plan.  Example `GET` request for retrieving the chain tip: ``` curl -X GET --header \"api-key: <your_project_api_key>\" https://mainnet.gomaestro-api.org/v0/chain-tip ```  Example `POST` request for submitting a transaction: ``` curl -X POST --header \"Content-Type: application/cbor\" --header \"api-key: <your_project_api_key>\" --data @tx.signed https://mainnet.gomaestro-api.org/v0/transactions ```

API version: V0
Contact: info@gomaestro.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ChainTip type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChainTip{}

// ChainTip Blockchain chain-tip (most recently adopted block)
type ChainTip struct {
	// Block hash of the most recent block
	BlockHash string `json:"block_hash"`
	// Height (number) of the most recent block
	Height int64 `json:"height"`
	// Absolute slot of the most recent block
	Slot int64 `json:"slot"`
}

// NewChainTip instantiates a new ChainTip object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChainTip(blockHash string, height int64, slot int64) *ChainTip {
	this := ChainTip{}
	this.BlockHash = blockHash
	this.Height = height
	this.Slot = slot
	return &this
}

// NewChainTipWithDefaults instantiates a new ChainTip object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChainTipWithDefaults() *ChainTip {
	this := ChainTip{}
	return &this
}

// GetBlockHash returns the BlockHash field value
func (o *ChainTip) GetBlockHash() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BlockHash
}

// GetBlockHashOk returns a tuple with the BlockHash field value
// and a boolean to check if the value has been set.
func (o *ChainTip) GetBlockHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockHash, true
}

// SetBlockHash sets field value
func (o *ChainTip) SetBlockHash(v string) {
	o.BlockHash = v
}

// GetHeight returns the Height field value
func (o *ChainTip) GetHeight() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *ChainTip) GetHeightOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *ChainTip) SetHeight(v int64) {
	o.Height = v
}

// GetSlot returns the Slot field value
func (o *ChainTip) GetSlot() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Slot
}

// GetSlotOk returns a tuple with the Slot field value
// and a boolean to check if the value has been set.
func (o *ChainTip) GetSlotOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slot, true
}

// SetSlot sets field value
func (o *ChainTip) SetSlot(v int64) {
	o.Slot = v
}

func (o ChainTip) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChainTip) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["block_hash"] = o.BlockHash
	toSerialize["height"] = o.Height
	toSerialize["slot"] = o.Slot
	return toSerialize, nil
}

type NullableChainTip struct {
	value *ChainTip
	isSet bool
}

func (v NullableChainTip) Get() *ChainTip {
	return v.value
}

func (v *NullableChainTip) Set(val *ChainTip) {
	v.value = val
	v.isSet = true
}

func (v NullableChainTip) IsSet() bool {
	return v.isSet
}

func (v *NullableChainTip) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChainTip(val *ChainTip) *NullableChainTip {
	return &NullableChainTip{value: val, isSet: true}
}

func (v NullableChainTip) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChainTip) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


